### ISSUE TITLE
Documentation format for CMake functions and macros

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CMakePP/CMakeDoc#13]
We need to decide how documentation should be generated for CMake functions. I propose following Sphinx's example, for example:
For:
```
#[[[
# This function has very basic documentation.
#
# This function's description stays close to idealized formatting and does not do
# anything fancy.

# :param person: The person this function says hi to
# :type person: string
#]]
function(say_hi_to person)
    message("Hi ${person}")
endfunction()
```

We generate:
```
.. function:: say_hi_to(person)

   This function has very basic documentation.

   This function's description stays close to idealized formatting and does not do
   anything fancy.

   :param person: The person this function says hi to
   :type person: string
```

Which renders (roughly) as:

**say_hi_to**(person)
&nbsp; &nbsp; &nbsp; This function has very basic documentation.

&nbsp; &nbsp; &nbsp; This function's description stays close to idealized formatting and does not do
&nbsp; &nbsp; &nbsp; anything fancy.
&nbsp; &nbsp; &nbsp; **Parameters:**
- _person_ (string) – The person this function says hi to

<br/><br/>
Since CMake is a loosely-typed language, doccomments require the `:type:` tag if the function depends on a typed variable. We will be able to extract this information automatically once CMakePP introduces strongly-typed variables and parameters.

# Macros
Sphinx does not support a `.. macro::` directive since Python does not have macros. We have three options:
1. Modify Sphinx to support macros by copying the function directive
2. Just use the `.. function::` directive as well and find some way to differentiate macros and functions
3. Use topics instead, ex:
```
.. topic:: macro **this_is_macro**(param1)
   This is a macro
```
The disadvantage of 3 is that `:param:` and `:type:` tags won't work as they are not valid topic options, instead we can use fields to emulate it, but the syntax in doccomments will differ.
<br/>
Personally, I suggest we go with 2 as it will still allow function-specific options like `:param:` to still work. Perhaps we could prepend text specifying this is a macro to the doccomment.

**Comment by ryanmrichard** [comment]
1. The format you have is what I've been adhering to (as long as the left border of `#` characters is allowed to be continuous and the brief can appear on the same line as the `#[[[` triglyph) so I approve :slightly_smiling_face: .

2. I don't think the strong types are going to help us unless the code is written using the CMakePP language (the CMakePP language is written in CMake, so we're still going to have to support the loose-typed use case).

3. For macros I like your suggestion of just reusing the `.. function` directive. It probably suffices to just put some boilerplate warning on the resulting reST like (pretending your `say_hi_to` function was actually a macro):

```.rst
.. function:: say_hi_to(person)
  
   .. warning:

      ``say_hi_to`` is a CMake macro and does **NOT** create a new scope.

   This function has very basic documentation.

   This function's description stays close to idealized formatting and does not do
   anything fancy.

   :param person: The person this function says hi to
   :type person: string
```

**Comment by AutonomicPerfectionist** [comment]
1. Right now the aggregator is setup to `lstrip()` all `#` and spaces from the doccomment, the first line also `lstrip()`s all `[` brackets and `rstrip()`s for the last line, so you can put the brief on both of those lines if you wish. 
Ex:
```
#[[[This works just fine
# As does this
as well as this
And this #]]
```

How do you mean by the left border of `#` being continuous?

**Comment by ryanmrichard** [comment]
By continuous I mean each line starts with a `#` character (your example doesn't put one on the blank line between the detailed description and the parameters).

Be careful with `lstrip()` in the body of the comment as reST has significant whitespace.

**Comment by AutonomicPerfectionist** [comment]
Ah, yes continuous hashmarks works just fine. The `lstrip()` will be changed to only strip the hashmarks in the next pull request, then we'll do custom processing to determine which style the doccomment uses. Ex:
If:
```
#[[[
# First non-whitespace line starts with a space
#]]

#[[[ Including in the opening bracket line
#]]
```
Then we remove a single space from the beginning of the line.
If
```
#[[[
#First line is against the left margin
With or without leading hashmarks
#]]
```
Then we don't remove any spaces on the left side.
This should allow for RST whitespace to work while maintaining multiple styles, so that this works
```
#[[[
This is an example without leading spaces
.. topic:: Test
   This is a test
#]]

#[[[
# This is an example with leading spaces
# .. topic:: Test
#    This is a test
#]]
```
