### ISSUE TITLE
PIP Package

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakeDoc#16]
#12 focuses on the fact that this is intended for use with C/C++ and CMake. Since this is a Python module it probably makes sense to have this be installable by the usual Python channels as well. Minimally that's PIP, but it may make sense to look into other Python package repos as well.

**Comment by AutonomicPerfectionist** [comment]
A single setup.py should work for pip and easy_install/setuptools installation, CMake support could be added fairly easily as well. We could also build Debian or RPM packages and upload them to repositories as well, if needed.

**Comment by AutonomicPerfectionist** [comment]
#19 adds a PIP-compatible setup.py, next step is to just upload, either I can do that or you can by running the setup.py register/bdist/sdist/upload commands.

**Comment by ryanmrichard** [comment]
I'd say let's worry about uploading it when all the repos are ready for a 1.0.
