### ISSUE TITLE
cmakedoc.cmake_regexer purpose strings should be enums

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [CMakePP/CMakeDoc#7]
Using plain strings (such as "block comment end") for processing is fragile, especially if these strings are not constants. Retyping these string literals everywhere will eventually lead to mistypes and unmaintainable code. Using enums allow greater flexibility, quick and easy comparisons, and easy extension for more purposes (if needed).

**Comment by ryanmrichard** [comment]
Honestly I'd probably throw away all the code I wrote in favor of using an actual parser/lexer, which fixes this problem :slightly_smiling_face:
